services:
  pgadmin:
    container_name: pgadmin_6_0
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  
      PGADMIN_DEFAULT_PASSWORD: admin123       
    ports:
      - '5050:80'
    networks:
      - inventoryManagement_network

networks:
  inventoryManagement_network:
    driver: bridge


